# ML-03 — Frame Your Lane as an ML Task

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Epinnn14/Flyrank-ML-Intern/blob/main/work/notebooks/w02_ml_task_framing.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

#LOAD DATA

In [34]:
import os
import sys
import subprocess

REPO_DIR = "Flyrank-ML-Intern"
IN_COLAB = "google.colab" in sys.modules
REPO_URL = "https://github.com/Epinnn14/Flyrank-ML-Intern"

if IN_COLAB:
    if not os.path.isdir(REPO_DIR):
        subprocess.run(
            ["git", "clone", "--depth", "1", REPO_URL, REPO_DIR],
            check=True
        )

    os.chdir(REPO_DIR)

    subprocess.run(
        [sys.executable, "-m", "pip", "install", "-q", "-r", "requirements.txt"],
        check=True,
    )

elif os.path.basename(os.getcwd()) == "notebooks":
    os.chdir("..")

In [35]:
import pandas as pd
import numpy as np

df = pd.read_csv("data/raw/content_refresh_anonymized.csv")

print("Dataset loaded successfully!")

print(f"Rows    : {df.shape[0]:,}")
print(f"Columns : {df.shape[1]}")

df.head()

Dataset loaded successfully!
Rows    : 30,000
Columns : 44

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

In [36]:
display(df[important_cols].describe(include="all"))

,client_id,content_id,content_type,clicks_90d,impressions_90d,ctr,engagement_rate,trend_direction
count,30000,30000,30000,30000.000000,30000.000000,30000.000000,30000.000000,30000
unique,32,30000,3,NaN,NaN,NaN,NaN,5
top,client_19581e27de,content_6880eb215048,keyword article,NaN,NaN,NaN,NaN,down
freq,7008,1,27207,NaN,NaN,NaN,NaN,16262
mean,NaN,NaN,NaN,16.097333,5200.366300,0.510733,2.534520,NaN
std,NaN,NaN,NaN,75.076958,16838.019547,3.279162,8.310096,NaN
min,NaN,NaN,NaN,0.000000,1.000000,0.000000,0.000000,NaN
25%,NaN,NaN,NaN,0.000000,81.000000,0.000000,0.000000,NaN
50%,NaN,NaN,NaN,1.000000,731.000000,0.070000,0.000000,NaN
75%,NaN,NaN,NaN,7.000000,3615.250000,0.290000,1.350000,NaN
max,NaN,NaN,NaN,4178.000000,517715.000000,100.000000,100.000000,NaN

## 1. My lane as an ML task (type)

**Task Type:** Classification

The goal of this project is to classify whether a content item is likely to be declining based on its historical performance signals. The model will help identify content that may require attention before its performance continues to decrease.

This is a supervised machine learning task because the model learns from labeled historical examples and predicts a categorical outcome.

In [37]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

task_type = "Classification"

print("ML Task Type:")
print(task_type)

print("\nDecision Supported:")
print("Identify content that is likely to be declining so editors can review it first.")

ML Task Type:
Classification

Decision Supported:
Identify content that is likely to be declining so editors can review it first.

## 2. Target or proxy

For this framing exercise, the target (proxy) is **trend_direction**.

Possible values include:

- down
- flat
- up

The target represents the recent performance trend of each content item.

In a production ML system, the preferred target would be an observed future outcome instead of a label derived from current information. For this exercise, trend_direction serves as an acceptable proxy for understanding the ML workflow.

In [38]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

target = "trend_direction"

print("Target Column:", target)
print()

display(df[target].value_counts(dropna=False))

print("\nExample Values")
display(df[[target]].head())

Target Column: trend_direction

trend_direction
down      16262
stable     5962
up         4388
new        2236
flat       1152
Name: count, dtype: int64

Example Values

  trend_direction
0            down
1            down
2            down
3          stable
4            down

## 3. Success metric

The primary evaluation metric is **F1-score**.

F1-score balances Precision and Recall, making it suitable when different classes may not appear equally often.

Additional metrics that can be monitored include:

- Precision
- Recall
- Accuracy

In [39]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

success_metric = "F1-score"

print("Selected Metric:", success_metric)

print("""
Reason:
- Balances Precision and Recall.
- Suitable for multi-class or imbalanced classification.
- More informative than Accuracy alone.
""")

Selected Metric: F1-score

Reason:
- Balances Precision and Recall.
- Suitable for multi-class or imbalanced classification.
- More informative than Accuracy alone.

## 4. The unit of analysis, as a real dataframe

The dataset contains one row for each content item.

Each row summarizes approximately 90 days of historical performance metrics, including search traffic, engagement, impressions, clicks, and other content characteristics.

Therefore:

**One row = One content item observed over the trailing 90-day window.**

In [40]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

print("Dataset Shape")
print(df.shape)

print("\nColumns")
display(df.columns.tolist())

print("\nUnit of Analysis")
print("One row = one content item.")

print("\nDataset Preview")
display(df.head())

important_cols = [
    "client_id",
    "content_id",
    "content_type",
    "clicks_90d",
    "impressions_90d",
    "ctr",
    "engagement_rate",
    "trend_direction",
]

display(df[important_cols].head())

print("\nTarget Distribution")
display(df["trend_direction"].value_counts())

Dataset Shape
(30000, 44)

Columns

['content_id',
 'client_id',
 'search_volume',
 'competition',
 'competition_level',
 'cpc',
 'content_type',
 'main_intent',
 'word_count',
 'char_count',
 'provider_used',
 'model_used',
 'impressions_90d',
 'clicks_90d',
 'pageviews_90d',
 'sessions_90d',
 'users_90d',
 'engaged_sessions_90d',
 'ai_sessions_90d',
 'scroll_events_90d',
 'days_with_impressions',
 'days_with_sessions',
 'impressions_last_30d',
 'clicks_last_30d',
 'sessions_last_30d',
 'impressions_prev_30d',
 'clicks_prev_30d',
 'sessions_prev_30d',
 'content_age_days',
 'age_tier',
 'age_tier_order',
 'days_since_last_update',
 'freshness_tier',
 'word_count_tier',
 'char_count_tier',
 'ctr',
 'avg_position',
 'engagement_rate',
 'scroll_rate',
 'ai_traffic_pct',
 'impression_tier',
 'position_tier',
 'trend_direction',
 'trend_pct']

Unit of Analysis
One row = one content item.

Dataset Preview

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

,client_id,content_id,content_type,clicks_90d,impressions_90d,ctr,engagement_rate,trend_direction
0,client_f369cb89fc,content_304f48230142,keyword article,29,3803,0.76,5.88,down
1,client_4e07408562,content_a1fb4e703a9e,keyword article,7,15320,0.05,0.00,down
2,client_7f2253d7e2,content_9aa793d4d895,keyword article,11,12581,0.09,0.00,down
3,client_19581e27de,content_331d6c4de07b,keyword article,58,11751,0.49,1.28,stable
4,client_3fdba35f04,content_d99b7a2d90ca,keyword article,24,19140,0.13,0.00,down

Target Distribution

trend_direction
down      16262
stable     5962
up         4388
new        2236
flat       1152
Name: count, dtype: int64

## 5. Why ML beats a fixed rule here

A fixed rule such as:

"If CTR is below 1%, then the content is declining"

is too simplistic because content performance depends on many factors at the same time.

Examples include:

- Click-through rate
- Search impressions
- Average search position
- Engagement rate
- Content age
- Content type
- User behavior

These variables interact in complex ways that are difficult to capture with manually written rules.

Machine learning can learn these patterns automatically from historical data and provide more accurate predictions than fixed thresholds.

The output of the model supports editors and content managers by helping them prioritize which content should be reviewed first.

The prediction supports content editors by helping them prioritize which pages should be reviewed or refreshed first. Instead of manually checking thousands of content items, the model highlights those that are most likely to require attention.

In [41]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

comparison = df[
    [
        "clicks_90d",
        "impressions_90d",
        "ctr",
        "engagement_rate",
        "trend_direction",
    ]
].copy()

# Simple rule:
comparison["rule_prediction"] = comparison["ctr"] < 1

display(comparison.head(10))

print("""
Observation

This simple rule only considers CTR.

However, content performance depends on multiple interacting signals,
including impressions, clicks, engagement rate, content type,
content age, search position, and many other variables.

Machine Learning can learn these complex relationships and produce
better predictions than a manually defined threshold.
""")

,clicks_90d,impressions_90d,ctr,engagement_rate,trend_direction,rule_prediction
0,29,3803,0.76,5.88,down,True
1,7,15320,0.05,0.00,down,True
2,11,12581,0.09,0.00,down,True
3,58,11751,0.49,1.28,stable,True
4,24,19140,0.13,0.00,down,True
5,1,3970,0.03,0.00,down,True
6,0,20,0.00,0.00,down,True
7,1,1724,0.06,3.57,stable,True
8,29,32574,0.09,5.88,down,True
9,2,1240,0.16,0.00,down,True

Observation

This simple rule only considers CTR.

However, content performance depends on multiple interacting signals,
including impressions, clicks, engagement rate, content type,
content age, search position, and many other variables.

Machine Learning can learn these complex relationships and produce
better predictions than a manually defined threshold.

## Self-check

Before you submit, confirm each line honestly:

- [x] Every section above is filled — markdown thinking AND the code that backs it
- [x] The notebook runs top to bottom with no errors (Runtime → Run all)
- [x] No client names, URLs, or private queries anywhere
- [x] My claims use careful words: observed, measured, directional, decision-support
- [x] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.